# espanso match file
matches:
  # Simple test snippet
  - trigger: ":espanso"
    replace: "Hi there from Brackenhurst!"
  
  # Today's date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  
  # All good note
  - trigger: ":cok"
    replace: "All good. No concerns. Eating/drinking well, no issues."
